### ISSUE TITLE
Unable to find download.sh

### ISSUE THREAD

**Issue by 66zhaofeng** [Eyr3/PrivacyAsst#1]
Hello, thank you very much for sharing. But I cannot find download.sh in the current file, and I hope to receive your reply.

#Download models Make sure that 'git lfs' is installed
CD models
Bash download.sh # required when 'conferenceMode' is' local 'or' hybrid '

**Comment by Eyr3** [comment]
Thanks for the question, I have uploaded the file to 'PrivacyAsst/server/models'.

**Comment by 66zhaofeng** [comment]
Hello, thank you very much for your answers and supplements. However, after downloading the model, I found that there was no tenseal model, so I couldn't find the file when running models.server.py. I also hope to receive your reply.

Traceback (most recent call last):
  File "models_server.py", line 16, in <module>
    from models.tenseal import ConvNet, EncConvNet
ModuleNotFoundError: No module named 'models.tenseal'

**Comment by Eyr3** [comment]
Here ConvNet, EncConvNet refers to the two classes in the files 'PrivacyAsst/server/models/tenseal/convnet.py' and 'PrivacyAsst/server/models/tenseal/encconvnet.py'. I have uploaded the folder 'PrivacyAsst/server/models/tenseal'.
